version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      ORIGIN: http://localhost:3000
      PORT: 4000
      SECRET: A3EF16171C3D3CC6
      GOOGLE_CLIENT_ID: 728156474147-7l3v2sf4l0mibr0sl56n0mjd09jti6lu.apps.googleusercontent.com
      MAILER_API_KEY: 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
      MONGODB_URI: mongodb://quevent_user:root_12345@db:27017/quevent
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: quevent_user
      MONGO_INITDB_ROOT_PASSWORD: root_12345
      MONGO_INITDB_DATABASE: quevent
    ports:
      - 27017:27017

