name: Build and Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Build
        working-directory: client
        run: |
          npm install
          npm run build
          mv build ../server/client
      - name: Login
        uses: actions/heroku@1.0.0
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Push
        uses: actions/heroku@1.0.0
        with:
          args: container:push -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        uses: actions/heroku@1.0.0
        with:
          args: container:release -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
